modLoader="javafml"

loaderVersion="[47,)"

license="${mod_license}"

issueTrackerURL="${mod_issue_tracker}"

# If your mod is purely client-side and has no multiplayer functionality (be it dedicated servers or Open to LAN),
# set this to true, and Forge will set the correct displayTest for you and skip loading your mod on dedicated servers.
#clientSideOnly=true #optional - defaults to false if absent

[[mods]]
modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

credits="${mod_credits}"

authors="${mod_authors}"

# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # if nothing is specified, MATCH_VERSION is the default when clientSideOnly=false, otherwise IGNORE_ALL_VERSION when clientSideOnly=true (#optional)

description='''Modpack mod that modifies Primal Winter and makes survival more difficult
Features:
- Primal Winter fog is fixed and can't be cheesed with render distance
- Snow layers take longer to mine in proportion to how stacked up they are
- Being in powder snow severely reduces mining speed
- Powder snow requires a shovel to break when stuck inside of it
- Powder snow can be broken faster using a shovel
- Snowy block variants added by Primal Winter take longer to mine
- Logs can't be mined without an axe
- Berry bushes, cacti, melon, pumpkin, and sugar cane no longer generate naturally
- Data-driven item tag for items that prevent sinking in powder snow'''

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="==1.20.1"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="primalwinter"
    mandatory=true
    versionRange="==5.0.0"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
